# Generated by ChatGPT for initial incidents app migration.
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("alert", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0.0)),
                ("reason", models.TextField()),
                ("attack_type", models.CharField(max_length=100)),
                ("severity", models.CharField(max_length=50)),
                ("summary", models.TextField()),
                ("recommendations", models.JSONField(default=dict)),
                ("signals", models.JSONField(default=dict)),
            ],
        ),
    ]
